# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
          only:
            - master
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.3
      #- image: circleci/openjdk:8u171-jdk-node-browsers
      - image: circleci/openjdk:8u171-jdk-node-browsers
      - image: circleci/android:api-27-alpha

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: whoami
      - run: npm --version
      - run: sudo npm install nativescript -g --unsafe-perm
      #- run: sudo apt-get install lib32z1 lib32ncurses5 libbz2-1.0:i386 libstdc++6:i386
      - run: sudo apt-get install g++
      - run: sudo apt-get install python-software-properties
      - run: sudo add-apt-repository ppa:webupd8team/java
      - run: sudo apt-get update
      - run: sudo apt-get install oracle-java8-installer
      - run: sudo update-alternatives --config java
      - run: tns doctor


      # run tests!
      - run: yarn test